### ISSUE TITLE
Service is not registered with Eureka Server

### ISSUE THREAD

**Issue by Sridharc20** [ziftytodd/gr8conf2016-config#1]
Hi Sir,
I was referring your presentation on "Spring Cloud Into Production" and trying to set up the Spring cloud micro-services on AWS ECS.

I was able to set up the Eureka (Including Replication). But the services are not registering with Eureka. This will be required so that the Feign clients can talk to other services via Eureka (Client Side Load balancing).

As we have configured config server - loadbalancer-Route53, Services & Eureka have this Route53 endpoints. But, we need eureka also to be binding with Route53 so that the services can locate the properties from config server and connect to the Eureka.

Please suggest.

**Comment by ziftytodd** [comment]
The code in this repo is 3 years old. I would assume that a number of changes in Spring and Netflix OSS has occurred during that time that would likely break the functionality here. I have not used Spring or Eureka in quite a while now, so unfortunately I am not able to provide any additional guidance.
